# Configuration file for ABV

# Barcodes should be strings, because leading zeros are not allowed
undoBarcode = "036000374575"
redoBarcode = "1234567"

# Set location of config files. Do not use trailing slash. Defaults to ~/.abv
#configPath = ~/etc/abv

# Set the web root directory (directory containing the front page html and the static/ folder). Do not use trailing slash. Defaults to /srv/http
#webRoot = ~/.abv/www

# Set the URL/IP Address of the abv API. Defaults to localhost
#apiUrl = "192.168.0.100"

[breweryNicknames]
"Abbaye Notre-Dame de Saint-Rémy"          = "Trappist Abbey of Rochefort"
"Ace Cider (The California Cider Company)" = "Ace Cider"
"Bayerische Staatsbrauerei Weihenstephan"  = "Weihenstephaner"
"Dogfish Head Craft Brewery"               = "Dogfish Head"
"Einstök Ölgerð"                           = "Einstök"
"Epic Brewing Co. (Utah, Colorado)"        = "Epic"
"Kirin Brewery Company"                    = "Kirin"

[beerNicknames]
"60 Minute IPA"                        = "60 Minute"
"A Little Sumpin' Sumpin' Ale"         = "Little Sumpin' Sumpin'"
"Ace - Dry Apple Craft Cider"          = "Dry Apple Craft Cider"
"Aloha Sculpin Hazy IPA"               = "Aloha Sculpin"
"Anchor Steam Beer"                    = "Anchor Steam"
"Barney Flats Oatmeal Stout"           = "Barney Flats"
"Black Butte Porter"                   = "Black Butte"
"Fresh Squeezed IPA"                   = "Fresh Squeezed"
"Hefeweizen Bavarian Wheat"            = "Bavarian Wheat"
"Heroine IPA"                          = "Heroine"
"Hop Henge Imperial IPA (2018)"        = "Hop Henge"
"Ichiban Shibori Premium"              = "Ichiban"
"Longboard Island Lager"               = "Longboard"
"Monk's Café Flemish Sour Ale"         = "Monk's Café"
"Organic California Blonde Ale"        = "California Blonde Ale"
"Oude Geuze (Vieille)"                 = "Oude Geuze"
"Scrimshaw Pilsner"                    = "Scrimshaw"
"Sin-Tax Imperial Peanut Butter Stout" = "Sin-Tax Peanut Butter Stout"
"Space Dust IPA"                       = "Space Dust"
"Stone Enjoy By 01.01.19 Brut IPA"     = "Enjoy By"
"Tart 'N Juicy Sour IPA"               = "Tart 'N Juicy"
"Weihenstephaner Hefeweissbier"        = "Weihenstephaner"
"Wildcide Hard Cider"                  = "Wildcide"

[styleNicknames]
"American Wild Ale"         = "Sour"
"Belgian Strong Dark Ale"   = "Belgian Dark"
"Belgian Strong Golden Ale" = "Belgian Golden"
"Pumpkin / Yam Beer"        = "Pumpkin Beer"
"Saison / Farmhouse Ale"    = "Farmhouse Ale"
"Shandy / Radler"           = "Shandy"
"Spiced / Herbed Beer"      = "Spiced Beer"
